[package]
name = "ensemble-migrations-example"
publish = false
version = "0.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1.32.0", features = ["full"] }
ensemble = { path = "../../ensemble", features = ["mysql"] }
