[package]
name = "ensemble-user-example"
publish = false
version = "0.0.0"
edition = "2021"


[dependencies]
tokio = { version = "1.32.0", features = ["full"] }
validator = { version = "0.16.1", features = ["derive"] }
ensemble = { path = "../../ensemble", features = ["mysql", "validator"] }
